version: "3.9"
services:
  node:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    user: node
    working_dir: /home/node/app
    command: bash -c "yarn && quasar dev"
